server {
 listen 80;
 root /usr/share/nginx/mobile;
 client_max_body_size 25m;
 add_header X-Content-Type-Options nosniff always;
 location / { try_files $uri $uri/ /index.html; }
 location /api/ { proxy_pass http://api:8080; proxy_read_timeout 120s; }
}
server {
 listen 81;
 root /usr/share/nginx/admin;
 client_max_body_size 25m;
 add_header X-Content-Type-Options nosniff always;
 location / { try_files $uri $uri/ /index.html; }
 location /api/ { proxy_pass http://api:8080; proxy_read_timeout 120s; }
}
