/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/learning/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["learning"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["save"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customer/me/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["account"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certification/applications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put: operations["resubmit"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["user"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/member-rules/{level}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["rule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/me/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["account_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/content/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["edit"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/captcha/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["challenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["practice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/targets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["target"];
        delete: operations["untarget"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/self-grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["selfGrade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/start/{paperId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customer/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customer/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customer/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customer/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certification/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["submit_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["identity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/imports/{id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["commit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminList"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/content/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["review"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/certifications/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["review_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["certificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["certificates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["learning_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customer/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attachments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["read_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/member-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/imports/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["schema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/imports/dictionary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dictionary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/certifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["audits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LearningRequest: {
            favorite: boolean;
            /** Format: int32 */
            progress?: number;
        };
        ApiResponseVoid: {
            code?: string;
            message?: string;
            data?: unknown;
            traceId?: string;
        };
        JsonNode: unknown;
        ApiResponseSaveAnswersResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["SaveAnswersResponse"];
            traceId?: string;
        };
        SaveAnswersResponse: {
            saved?: boolean;
            /** Format: date-time */
            serverTime?: string;
        };
        AccountRequest: {
            username: string;
            currentPassword: string;
            newPassword: string;
        };
        ApplicationRequest: {
            /** Format: uuid */
            certificateId: string;
            holderName: string;
            number: string;
            numberType: string;
            /** Format: date */
            obtainedOn: string;
            /** Format: uuid */
            attachmentId: string;
            /** Format: uuid */
            auxiliaryId?: string;
            note?: string;
        };
        ApiResponseIdResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["IdResponse"];
            traceId?: string;
        };
        IdResponse: {
            /** Format: uuid */
            id?: string;
        };
        UserUpdateRequest: {
            enabled: boolean;
        };
        MemberRuleRequest: {
            name: string;
            icon: string;
            /** Format: int32 */
            sort: number;
            entitlements?: components["schemas"]["JsonNode"];
        };
        ContentRequest: {
            kind: string;
            namespace: string;
            externalId: string;
            payload: components["schemas"]["JsonNode"];
        };
        ApiResponseSaveContentResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["SaveContentResponse"];
            traceId?: string;
        };
        SaveContentResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            version?: number;
            skipped?: boolean;
        };
        AdminUpdateRequest: {
            username: string;
            role: string;
            enabled: boolean;
        };
        CaptchaChallengeRequest: {
            /** @enum {string} */
            scene: "CUSTOMER_LOGIN" | "ADMIN_LOGIN" | "CUSTOMER_REGISTER";
            username: string;
        };
        ApiResponseCaptchaChallengeResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["CaptchaChallengeResponse"];
            traceId?: string;
        };
        CaptchaChallengeResponse: {
            challengeId?: string;
            background?: string;
            piece?: string;
            /** Format: int32 */
            width?: number;
            /** Format: int32 */
            height?: number;
            /** Format: int32 */
            pieceWidth?: number;
            /** Format: int32 */
            pieceHeight?: number;
            /** Format: int32 */
            pieceY?: number;
            /** Format: int32 */
            expiresIn?: number;
        };
        PracticeRequest: {
            /** Format: int32 */
            count?: number;
            certificateCode?: string;
            type?: string;
            difficulty?: string;
            subject?: string;
            chapter?: string;
            knowledgeCode?: string;
            wrongOnly?: boolean;
        };
        ApiResponseExamResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["ExamResponse"];
            traceId?: string;
        };
        ExamResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            /** Format: uuid */
            paperId?: string;
            snapshot?: components["schemas"]["JsonNode"];
            answers?: components["schemas"]["JsonNode"];
            result?: components["schemas"]["JsonNode"];
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            deadline?: string;
            /** Format: date-time */
            submittedAt?: string;
            status?: string;
            /** Format: date-time */
            serverTime?: string;
        };
        CaptchaAnswer: {
            challengeId: string;
            /** Format: double */
            offsetX: number;
        };
        LoginRequest: {
            username: string;
            password: string;
            captcha?: components["schemas"]["CaptchaAnswer"];
        };
        ApiResponseTokenResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["TokenResponse"];
            traceId?: string;
        };
        TokenResponse: {
            accessToken?: string;
            refreshToken?: string;
            /** Format: int32 */
            expiresIn?: number;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        ApiResponseAttachmentResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["AttachmentResponse"];
            traceId?: string;
        };
        AttachmentResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            type?: string;
            /** Format: int64 */
            size?: number;
        };
        IdentityRequest: {
            holderName: string;
            evidence: string;
        };
        ApiResponseImportBatchResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["ImportBatchResponse"];
            traceId?: string;
        };
        ImportBatchResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            ownerId?: string;
            idempotencyKey?: string;
            checksum?: string;
            status?: string;
            payload?: components["schemas"]["JsonNode"];
            report?: components["schemas"]["JsonNode"];
            /** Format: date-time */
            createdAt?: string;
            allowUpdates?: boolean;
        };
        ImportCommitRequest: {
            allowUpdates?: boolean;
        };
        ContentReviewRequest: {
            /** Format: int32 */
            version: number;
            status: string;
            reason: string;
        };
        CertificateReviewRequest: {
            action: string;
            reason: string;
            officialResult?: string;
            officialSource?: string;
            evidence?: string;
            ownershipEvidence?: string;
            ownershipConfirmed?: boolean;
        };
        CertificateRequest: {
            /** Format: uuid */
            id?: string;
            code: string;
            name: string;
            specialty: string;
            /** Format: int32 */
            level: number;
        };
        AdminCreateRequest: {
            username: string;
            password: string;
            role: string;
            enabled: boolean;
        };
        ApiResponseListCertificateResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["CertificateResponse"][];
            traceId?: string;
        };
        CertificateResponse: {
            /** Format: uuid */
            id?: string;
            code?: string;
            name?: string;
            examSystem?: string;
            specialty?: string;
            /** Format: int32 */
            level?: number;
            enabled?: boolean;
        };
        PageQuery: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string;
            direction?: string;
            /** Format: int64 */
            offset?: number;
        };
        ApiResponsePageResponseLearningResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["PageResponseLearningResponse"];
            traceId?: string;
        };
        LearningResponse: {
            /** Format: uuid */
            userId?: string;
            /** Format: uuid */
            entityId?: string;
            /** Format: int32 */
            version?: number;
            favorite?: boolean;
            wrong?: boolean;
            /** Format: int32 */
            progress?: number;
            /** Format: date-time */
            updatedAt?: string;
            title?: string;
        };
        PageResponseLearningResponse: {
            records?: components["schemas"]["LearningResponse"][];
            /** Format: int64 */
            total?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
        };
        ApiResponsePageResponseExamSummaryResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["PageResponseExamSummaryResponse"];
            traceId?: string;
        };
        ExamSummaryResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            paperId?: string;
            status?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            deadline?: string;
            result?: components["schemas"]["JsonNode"];
        };
        PageResponseExamSummaryResponse: {
            records?: components["schemas"]["ExamSummaryResponse"][];
            /** Format: int64 */
            total?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
        };
        ApiResponseProfileResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["ProfileResponse"];
            traceId?: string;
        };
        BadgeResponse: {
            name?: string;
            /** Format: int32 */
            level?: number;
            specialty?: string;
            /** Format: date-time */
            certifiedAt?: string;
        };
        LevelHistoryResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            /** Format: int32 */
            oldLevel?: number;
            /** Format: int32 */
            newLevel?: number;
            /** Format: uuid */
            applicationId?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        MemberRuleResponse: {
            /** Format: int32 */
            level?: number;
            name?: string;
            icon?: string;
            /** Format: int32 */
            sortOrder?: number;
            entitlements?: components["schemas"]["JsonNode"];
        };
        ProfileResponse: {
            /** Format: uuid */
            id?: string;
            username?: string;
            role?: string;
            identityVerified?: boolean;
            /** Format: int32 */
            memberLevel?: number;
            badges?: components["schemas"]["BadgeResponse"][];
            targets?: components["schemas"]["CertificateResponse"][];
            rules?: components["schemas"]["MemberRuleResponse"][];
            history?: components["schemas"]["LevelHistoryResponse"][];
        };
        ApiResponsePageResponseContentResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["PageResponseContentResponse"];
            traceId?: string;
        };
        ContentResponse: {
            /** Format: uuid */
            id?: string;
            kind?: string;
            namespace?: string;
            externalId?: string;
            /** Format: int32 */
            currentVersion?: number;
            title?: string;
            payload?: components["schemas"]["JsonNode"];
            status?: string;
            /** Format: int32 */
            version?: number;
        };
        PageResponseContentResponse: {
            records?: components["schemas"]["ContentResponse"][];
            /** Format: int64 */
            total?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
        };
        ApiResponsePageResponseApplicationResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["PageResponseApplicationResponse"];
            traceId?: string;
        };
        ApplicationResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            /** Format: uuid */
            certificateId?: string;
            certificateName?: string;
            username?: string;
            holderName?: string;
            number?: string;
            numberType?: string;
            /** Format: date */
            obtainedOn?: string;
            /** Format: uuid */
            attachmentId?: string;
            /** Format: uuid */
            auxiliaryId?: string;
            note?: string;
            /** Format: int32 */
            revision?: number;
            autoResult?: string;
            autoDetails?: components["schemas"]["JsonNode"];
            officialResult?: string;
            status?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            reviews?: components["schemas"]["ReviewResponse"][];
            verifications?: components["schemas"]["VerificationResponse"][];
        };
        PageResponseApplicationResponse: {
            records?: components["schemas"]["ApplicationResponse"][];
            /** Format: int64 */
            total?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
        };
        ReviewResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            applicationId?: string;
            /** Format: uuid */
            reviewerId?: string;
            action?: string;
            reason?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        VerificationResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            applicationId?: string;
            /** Format: uuid */
            reviewerId?: string;
            result?: string;
            officialSource?: string;
            evidence?: string;
            ownershipEvidence?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ApiResponseApplicationResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["ApplicationResponse"];
            traceId?: string;
        };
        ApiResponsePageResponseUserResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["PageResponseUserResponse"];
            traceId?: string;
        };
        PageResponseUserResponse: {
            records?: components["schemas"]["UserResponse"][];
            /** Format: int64 */
            total?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
        };
        UserResponse: {
            /** Format: uuid */
            id?: string;
            username?: string;
            role?: string;
            enabled?: boolean;
            identityVerified?: boolean;
            /** Format: int32 */
            memberLevel?: number;
        };
        ApiResponseListMemberRuleResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["MemberRuleResponse"][];
            traceId?: string;
        };
        AdminResponse: {
            /** Format: uuid */
            id?: string;
            username?: string;
            role?: string;
            enabled?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponseAdminResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["AdminResponse"];
            traceId?: string;
        };
        ApiResponsePageResponseImportBatchResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["PageResponseImportBatchResponse"];
            traceId?: string;
        };
        PageResponseImportBatchResponse: {
            records?: components["schemas"]["ImportBatchResponse"][];
            /** Format: int64 */
            total?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
        };
        ImportDictionaryResponse: {
            certificates?: components["schemas"]["CertificateResponse"][];
            knowledge?: components["schemas"]["ContentResponse"][];
            syllabus?: components["schemas"]["ContentResponse"][];
        };
        ApiResponsePageResponseAuditResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["PageResponseAuditResponse"];
            traceId?: string;
        };
        AuditResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            actorId?: string;
            /** Format: uuid */
            adminActorId?: string;
            action?: string;
            /** Format: uuid */
            targetId?: string;
            detail?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        PageResponseAuditResponse: {
            records?: components["schemas"]["AuditResponse"][];
            /** Format: int64 */
            total?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
        };
        AdminQuery: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string;
            direction?: string;
            username?: string;
            role?: string;
            enabled?: boolean;
            /** Format: int64 */
            offset?: number;
        };
        ApiResponsePageResponseAdminResponse: {
            code?: string;
            message?: string;
            data?: components["schemas"]["PageResponseAdminResponse"];
            traceId?: string;
        };
        PageResponseAdminResponse: {
            records?: components["schemas"]["AdminResponse"][];
            /** Format: int64 */
            total?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    learning: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    save: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: components["schemas"]["JsonNode"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSaveAnswersResponse"];
                };
            };
        };
    };
    account: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseApplicationResponse"];
                };
            };
        };
    };
    resubmit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseIdResponse"];
                };
            };
        };
    };
    user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                level: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberRuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    account_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    edit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSaveContentResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    challenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptchaChallengeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCaptchaChallengeResponse"];
                };
            };
        };
    };
    practice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamResponse"];
                };
            };
        };
    };
    target: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    untarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamResponse"];
                };
            };
        };
    };
    selfGrade: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: number;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamResponse"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paperId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTokenResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTokenResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTokenResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query: {
                query: components["schemas"]["PageQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseApplicationResponse"];
                };
            };
        };
    };
    submit_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseIdResponse"];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: {
                access?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAttachmentResponse"];
                };
            };
        };
    };
    identity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    logout_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query: {
                query: components["schemas"]["PageQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseImportBatchResponse"];
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseImportBatchResponse"];
                };
            };
        };
    };
    commit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportCommitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseImportBatchResponse"];
                };
            };
        };
    };
    adminList: {
        parameters: {
            query: {
                kind?: string;
                query: components["schemas"]["PageQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseContentResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSaveContentResponse"];
                };
            };
        };
    };
    review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentReviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    review_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CertificateReviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    certificate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CertificateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseIdResponse"];
                };
            };
        };
    };
    refresh_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTokenResponse"];
                };
            };
        };
    };
    login_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTokenResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query: {
                query: components["schemas"]["AdminQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseAdminResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseIdResponse"];
                };
            };
        };
    };
    certificates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListCertificateResponse"];
                };
            };
        };
    };
    learning_1: {
        parameters: {
            query: {
                query: components["schemas"]["PageQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseLearningResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query: {
                query: components["schemas"]["PageQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseExamSummaryResponse"];
                };
            };
        };
    };
    read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProfileResponse"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query: {
                kind?: string;
                query: components["schemas"]["PageQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseContentResponse"];
                };
            };
        };
    };
    read_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    users: {
        parameters: {
            query: {
                query: components["schemas"]["PageQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseUserResponse"];
                };
            };
        };
    };
    list_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListMemberRuleResponse"];
                };
            };
        };
    };
    me_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminResponse"];
                };
            };
        };
    };
    schema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JsonNode"];
                };
            };
        };
    };
    dictionary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImportDictionaryResponse"];
                };
            };
        };
    };
    queue: {
        parameters: {
            query: {
                query: components["schemas"]["PageQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseApplicationResponse"];
                };
            };
        };
    };
    audits: {
        parameters: {
            query: {
                query: components["schemas"]["PageQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseAuditResponse"];
                };
            };
        };
    };
}
